package net.scandicraft.items.register;

import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.scandicraft.items.ScandiumBow;
import net.scandicraft.items.ScepterRepair;
import net.scandicraft.items.ScepterSpawnCreeper;

public class ScandiCraftItems {

    public static final Item scandium;
    public static final Item pyrite;
    public static final Item lazurite;
    public static final Item scandium_sword;
    public static final Item scandium_shovel;
    public static final Item scandium_pickaxe;
    public static final Item scandium_axe;
    public static final Item scandium_hoe;
    public static final Item pyrite_sword;
    public static final Item pyrite_shovel;
    public static final Item pyrite_pickaxe;
    public static final Item pyrite_axe;
    public static final Item pyrite_hoe;
    public static final Item lazurite_sword;
    public static final Item lazurite_shovel;
    public static final Item lazurite_pickaxe;
    public static final Item lazurite_axe;
    public static final Item lazurite_hoe;
    public static final ItemArmor scandium_helmet;
    public static final ItemArmor scandium_chestplate;
    public static final ItemArmor scandium_leggings;
    public static final ItemArmor scandium_boots;
    public static final ItemArmor pyrite_helmet;
    public static final ItemArmor pyrite_chestplate;
    public static final ItemArmor pyrite_leggings;
    public static final ItemArmor pyrite_boots;
    public static final ItemArmor lazurite_helmet;
    public static final ItemArmor lazurite_chestplate;
    public static final ItemArmor lazurite_leggings;
    public static final ItemArmor lazurite_boots;
    public static final ItemArmor bloody_helmet;
    public static final ItemArmor bloody_chestplate;
    public static final ItemArmor bloody_leggings;
    public static final ItemArmor bloody_boots;
    public static final Item bloody_sword;
    public static final ScepterSpawnCreeper scepter_creeper;
    public static final ScepterRepair scepter_repair;
    public static final Item pyrite_pie;
    public static final Item lazurite_bread;
    public static final ScandiumBow scandium_bow;
    public static final Item scandivote;
    public static final Item scandibox;

    static {
        scandium = Items.getRegisteredItem("scandium");
        pyrite = Items.getRegisteredItem("pyrite");
        lazurite = Items.getRegisteredItem("lazurite");
        scandium_sword = Items.getRegisteredItem("scandium_sword");
        scandium_shovel = Items.getRegisteredItem("scandium_shovel");
        scandium_pickaxe = Items.getRegisteredItem("scandium_pickaxe");
        scandium_axe = Items.getRegisteredItem("scandium_axe");
        scandium_hoe = Items.getRegisteredItem("scandium_hoe");
        pyrite_sword = Items.getRegisteredItem("pyrite_sword");
        pyrite_shovel = Items.getRegisteredItem("pyrite_shovel");
        pyrite_pickaxe = Items.getRegisteredItem("pyrite_pickaxe");
        pyrite_axe = Items.getRegisteredItem("pyrite_axe");
        pyrite_hoe = Items.getRegisteredItem("pyrite_hoe");
        lazurite_sword = Items.getRegisteredItem("lazurite_sword");
        lazurite_shovel = Items.getRegisteredItem("lazurite_shovel");
        lazurite_pickaxe = Items.getRegisteredItem("lazurite_pickaxe");
        lazurite_axe = Items.getRegisteredItem("lazurite_axe");
        lazurite_hoe = Items.getRegisteredItem("lazurite_hoe");
        scandium_helmet = (ItemArmor) Items.getRegisteredItem("scandium_helmet");
        scandium_chestplate = (ItemArmor) Items.getRegisteredItem("scandium_chestplate");
        scandium_leggings = (ItemArmor) Items.getRegisteredItem("scandium_leggings");
        scandium_boots = (ItemArmor) Items.getRegisteredItem("scandium_boots");
        pyrite_helmet = (ItemArmor) Items.getRegisteredItem("pyrite_helmet");
        pyrite_chestplate = (ItemArmor) Items.getRegisteredItem("pyrite_chestplate");
        pyrite_leggings = (ItemArmor) Items.getRegisteredItem("pyrite_leggings");
        pyrite_boots = (ItemArmor) Items.getRegisteredItem("pyrite_boots");
        lazurite_helmet = (ItemArmor) Items.getRegisteredItem("lazurite_helmet");
        lazurite_chestplate = (ItemArmor) Items.getRegisteredItem("lazurite_chestplate");
        lazurite_leggings = (ItemArmor) Items.getRegisteredItem("lazurite_leggings");
        lazurite_boots = (ItemArmor) Items.getRegisteredItem("lazurite_boots");
        bloody_helmet = (ItemArmor) Items.getRegisteredItem("bloody_helmet");
        bloody_chestplate = (ItemArmor) Items.getRegisteredItem("bloody_chestplate");
        bloody_leggings = (ItemArmor) Items.getRegisteredItem("bloody_leggings");
        bloody_boots = (ItemArmor) Items.getRegisteredItem("bloody_boots");
        bloody_sword = Items.getRegisteredItem("bloody_sword");
        scepter_creeper = (ScepterSpawnCreeper) Items.getRegisteredItem("scepter_creeper");
        scepter_repair = (ScepterRepair) Items.getRegisteredItem("scepter_repair");
        pyrite_pie = Items.getRegisteredItem("pyrite_pie");
        lazurite_bread = Items.getRegisteredItem("lazurite_bread");
        scandium_bow = (ScandiumBow) Items.getRegisteredItem("scandium_bow");
        scandivote = Items.getRegisteredItem("scandivote");
        scandibox = Items.getRegisteredItem("scandibox");
    }

}
